
<footer>
        <div class="row">
            <div class="column_one">
                <a href="index.html" class="logo1">Debugallica</a>
                <p class="description">
                    Check us now to see the future of IT technologies in your hands.
                </p>
            </div>
            <div class="column_two">
                <h3 class="email">Contact Us via Email</h3>
                <div class="mail">
                    <a href="mailto:105555880@student.swin.edu.au" class="btnf">Mai Chi</a>
                    <a href="mailto:105559691@astudent.swin.edu.au" class="btnf">Duc Minh</a>
                    <a href="mailto:105550568@student.swin.edu.au" class="btnf">Anh Duc</a>
                    <a href="mailto:105560253@student.swin.edu.au" class="btnf">Khac Phi</a>
                </div>
                <h3 class="connect">Follow Our Socials</h3>
                <ul class="socials">
                    <li class="media"><img src="images/instagram.png" alt="Instagram"><a href="https://www.instagram.com/swinburne/"><p>&nbsp;Instagram</p></a></li>
                    <li class="media"><img src="images/facebook.png" alt="Facebook"><a href="https://www.facebook.com/swinburneuniversityoftechnology"><p>&nbsp;Facebook</p></a></li>
                    <li class="media"><img src="images/x.png" alt="X"><a href="https://x.com/Swinburne"><p>&nbsp;X</p></a></li>
                </ul>
            </div>

            <div class="column_three">
                <h3 class="mapping_one">Where to Find Us</h3>
                <h4 class="mapping_two">Click on the Map for More Information</h4>
                <div class="map-container">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.0276387232884!2d105.78045937444972!3d21.03158008061841!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135bfa667a7dee9%3A0x2ac9ba5f99e4f389!2sSwinburne%20Innovation%20Space!5e0!3m2!1svi!2s!4v1742855355006!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
</footer>
