<!DOCTYPE php>
<html lang="en">
<head>
   <link rel="stylesheet" href="styles\styleheader.css">
</head>
<!-- ---Header--- -->
<header>
    <a href ="index.php" class="logo"> Debugallica </a>
    <a href="inc/login.php" class="login">Log In</a>
    <a href="#" class="login">Sign Up</a>
    <div class="menu" onclick=showSidebar()><img src="images\mingcute_menu-fill.svg" width="30"></div>
</header>

