<nav>
    <div class="nav-links">
    <ul class="sidebar">
        <li class="close" onclick=hideSidebar()><img src="images\close.svg" width="26"></li>
        <li><a href="index.php"> Home</a></li>
        <li><a href="jobs.php">Jobs&nbspInfo</a></li>
        <li><a href="apply.php"> Apply Now! </a></li>
        <li><a href="abouts.php"> About Us </a></li>
        <li><a href="loginmanager.php"> Management </a></li>
        <li><a href="#"> Enhancement 1 </a></li>
        <li><a href="#"> Enhancement 2 </a></li>
    </ul>
    </div>
</nav>